baseURL = "https://beta.safespring.eu/"
author = "Safespring"
copyright = "2025 Safespring"

# Pagination
pagination.pagerSize = 10
pagination.path = "latest"

#------------------------------------------------------------------------------
# Languages
#------------------------------------------------------------------------------
defaultContentLanguage = 'sv'

[languages]
  [languages.en]
  languageCode = 'en-GB'
  languageName = 'English'
  title = 'Empowering European Innovation'
  weight = 1
  baseURL = 'https://beta.safespring.eu/'
  [languages.en.permalinks]
    [languages.en.permalinks.page]
      books = '/books/:slug/'
    [languages.en.permalinks.section]
      books = '/books/'

  [languages.sv]
  languageCode = 'sv-SE'
  languageName = 'Svenska'
  title = 'Stärk europeisk innovation'
  weight = 2
  baseURL = 'https://beta.safespring.se/'
  [languages.sv.permalinks]
    [languages.sv.permalinks.page]
      documents = '/dokument/:contentbasename/'
      industries = '/branscher/:contentbasename/'
      knowledge-hub = 'kunskapshubb/:contentbasename/'
      services = '/tjanster/:contentbasename/'
    [languages.sv.permalinks.section]
      documents = '/dokument/'
      industries = '/branscher/'
      services = '/tjanster/'

  [languages.nb]
  languageCode = 'nb-NO'
  languageName = 'Norsk (Bokmål)'
  title = 'Styrke europeisk innovasjon'
  weight = 3
  baseURL = 'https://beta.safespring.no/'
  [languages.nb.permalinks]
    [languages.nb.permalinks.page]
      books = '/books/:slug/'
    [languages.nb.permalinks.section]
      books = '/books/'

  [languages.da]
  languageCode = 'da-DK'
  languageName = 'Dansk'
  title = 'Styrkelse af europæisk innovation'
  weight = 4
  baseURL = 'https://beta.safespring.dk/'
  [languages.da.permalinks]
    [languages.da.permalinks.page]
      books = '/books/:slug/'
    [languages.da.permalinks.section]
      books = '/books/'

#------------------------------------------------------------------------------
# Content mounts
#------------------------------------------------------------------------------

# SV content
[[module.mounts]]
source = 'content/sv'
target = 'content'
lang = 'sv'

# NB content
[[module.mounts]]
source = 'content/nb'
target = 'content'
lang = 'nb'

# DA content
[[module.mounts]]
source = 'content/da'
target = 'content'
lang = 'da'

# EN content
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'en'



[params]

  mainSections = ['blog', 'webinar', 'whitepaper', 'solution-brief']

[sitemap]
    changefreq = "daily"
    filename = "sitemap.xml"
    priority = 0.5

[outputs]
    home = ["HTML", "RSS", "SITEMAP"]

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'igor'
    tabWidth = 4
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
  [markup.goldmark.extensions]
    footnote = true

[blackfriday]
fractions = false

[minify]
  minifyOutput = true
