baseURL = "https://beta.safespring.eu/"
author = "Safespring"
copyright = "2025 Safespring"

# Pagination
[pagination]
  pagerSize = 10
  path = "latest"

#------------------------------------------------------------------------------
# Languages
#------------------------------------------------------------------------------
defaultContentLanguage = 'sv'

[languages]
  [languages.en]
  languageCode = 'en-GB'
  languageName = 'English'
  title = 'Empowering European Innovation'
  weight = 1
  baseURL = 'https://beta.safespring.eu/'
  [languages.en.permalinks]
    [languages.en.permalinks.page]
      books = '/books/:slug/'
      services = '/services/:slug/'
      blog = '/blog/:slug/'
      'tech-update' = '/tech-update/:slug/'
      webinar = '/webinar/:slug/'
      whitepaper = '/whitepaper/:slug/'
      'solution-brief' = '/solution-brief/:slug/'
      industries = '/industries/:slug/'
      documents = '/documents/:slug/'
      career = '/career/:slug/'
      demo = '/demo/:slug/'
      geant = '/geant/:slug/'
      onboarding = '/onboarding/:slug/'
      saas = '/saas/:slug/'
    [languages.en.permalinks.section]
      books = '/books/'
      services = '/services/'
      blog = '/blog/'
      'tech-update' = '/tech-update/'
      webinar = '/webinar/'
      whitepaper = '/whitepaper/'
      'solution-brief' = '/solution-brief/'
      industries = '/industries/'
      documents = '/documents/'
      career = '/career/'
      demo = '/demo/'
      geant = '/geant/'
      onboarding = '/onboarding/'
      saas = '/saas/'

  [languages.sv]
  languageCode = 'sv-SE'
  languageName = 'Svenska'
  title = 'Stärk europeisk innovation'
  weight = 2
  baseURL = 'https://beta.safespring.se/'
  [languages.sv.permalinks]
    [languages.sv.permalinks.page]
      documents = '/dokument/:slug/'
      industries = '/branscher/:slug/'
      blog = '/blogg/:slug/'
      'tech-update' = '/tekniska-uppdateringar/:slug/'
      webinar = '/webinar/:slug/'
      whitepaper = '/vitbok/:slug/'
      'solution-brief' = '/losningsfaktablad/:slug/'
      services = '/tjanster/:slug/'
      career = '/karriar/:slug/'
      demo = '/demo/:slug/'
      geant = '/geant/:slug/'
      onboarding = '/onboarding/:slug/'
      saas = '/saas/:slug/'
    [languages.sv.permalinks.section]
      documents = '/dokument/'
      industries = '/branscher/'
      blog = '/blogg/'
      'tech-update' = '/tekniska-uppdateringar/'
      webinar = '/webinar/'
      whitepaper = '/vitbok/'
      'solution-brief' = '/losningsfaktablad/'
      services = '/tjanster/'
      career = '/karriar/'
      demo = '/demo/'
      geant = '/geant/'
      onboarding = '/onboarding/'
      saas = '/saas/'

  [languages.nb]
  languageCode = 'nb-NO'
  languageName = 'Norsk (Bokmål)'
  title = 'Styrke europeisk innovasjon'
  weight = 3
  baseURL = 'https://beta.safespring.no/'
  [languages.nb.permalinks]
    [languages.nb.permalinks.page]
      books = '/books/:slug/'
      services = '/tjenester/:slug/'
      blog = '/blogg/:slug/'
      'tech-update' = '/tekniske-oppdateringer/:slug/'
      webinar = '/webinar/:slug/'
      whitepaper = '/hvitbok/:slug/'
      'solution-brief' = '/losningsfaktablad/:slug/'
      industries = '/industrier/:slug/'
      documents = '/dokumenter/:slug/'
      demo = '/demo/:slug/'
      onboarding = '/onboarding/:slug/'
      saas = '/saas/:slug/'
    [languages.nb.permalinks.section]
      books = '/books/'
      services = '/tjenester/'
      blog = '/blogg/'
      'tech-update' = '/tekniske-oppdateringer/'
      webinar = '/webinar/'
      whitepaper = '/hvitbok/'
      'solution-brief' = '/losningsfaktablad/'
      industries = '/industrier/'
      documents = '/dokumenter/'
      demo = '/demo/'
      onboarding = '/onboarding/'
      saas = '/saas/'

  [languages.da]
  languageCode = 'da-DK'
  languageName = 'Dansk'
  title = 'Styrkelse af europæisk innovation'
  weight = 4
  baseURL = 'https://beta.safespring.dk/'
  [languages.da.permalinks]
    [languages.da.permalinks.page]
      books = '/books/:slug/'
      services = '/tjenester/:slug/'
      blog = '/blog/:slug/'
      'tech-update' = '/tekniske-opdateringer/:slug/'
      webinar = '/webinar/:slug/'
      whitepaper = '/hvidbog/:slug/'
      'solution-brief' = '/losningsfaktablad/:slug/'
      industries = '/industrier/:slug/'
      documents = '/dokumenter/:slug/'
      demo = '/demo/:slug/'
      onboarding = '/onboarding/:slug/'
      saas = '/saas/:slug/'
    [languages.da.permalinks.section]
      books = '/books/'
      services = '/tjenester/'
      blog = '/blog/'
      'tech-update' = '/tekniske-opdateringer/'
      webinar = '/webinar/'
      whitepaper = '/hvidbog/'
      'solution-brief' = '/losningsfaktablad/'
      industries = '/industrier/'
      documents = '/dokumenter/'
      demo = '/demo/'
      onboarding = '/onboarding/'
      saas = '/saas/'

#------------------------------------------------------------------------------
# Content mounts
#------------------------------------------------------------------------------

# SV content
[[module.mounts]]
source = 'content/sv'
target = 'content'
lang = 'sv'

# NB content
[[module.mounts]]
source = 'content/nb'
target = 'content'
lang = 'nb'

# DA content
[[module.mounts]]
source = 'content/da'
target = 'content'
lang = 'da'

# EN content
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'en'



[params]

  mainSections = ['blog', 'webinar', 'whitepaper', 'solution-brief']

[sitemap]
    changefreq = "daily"
    filename = "sitemap.xml"
    priority = 0.5

[outputs]
    home = ["HTML", "RSS", "SITEMAP"]

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'igor'
    tabWidth = 4
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
  [markup.goldmark.extensions]
    footnote = true

[blackfriday]
fractions = false

[minify]
  minifyOutput = true
