baseURL = "https://www.safespring.com/"
author = "Safespring"
copyright = "2025 Safespring"

# Pagination
paginate = 10
paginatePath = "latest"

#------------------------------------------------------------------------------
# Languages
#------------------------------------------------------------------------------
defaultContentLanguage = 'en'


[languages.en]
languageCode = 'en-GB'
languageName = 'English'
title = 'Empowering European Innovation'
weight = 1
#baseURL = 'https://safespring.com/'


[languages.sv]
languageCode = 'sv-SE'
languageName = 'Svenska'
title = 'Stärk europeisk innovation'
weight = 2
#baseURL = 'https://safespring.se/'

[languages.nb]
languageCode = 'nb-NO'
languageName = 'Norsk (Bokmål)'
title = 'Styrke europeisk innovasjon'
weight = 3
#baseURL = 'https://safespring.no/'

[languages.da]
languageCode = 'da-DK'
languageName = 'Dansk'
title = 'Styrkelse af europæisk innovation'
weight = 4
#baseURL = 'https://safespring.dk/'

#------------------------------------------------------------------------------
# Content mounts
#------------------------------------------------------------------------------

# SV content
[[module.mounts]]
source = 'content/sv'
target = 'content'
lang = 'sv'

# EN content
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'en'

# NB content
[[module.mounts]]
source = 'content/nb'
target = 'content'
lang = 'nb'

# DA content
[[module.mounts]]
source = 'content/da'
target = 'content'
lang = 'da'

#------------------------------------------------------------------------------
# Fill in the missing translations
#------------------------------------------------------------------------------

# This fills in the gaps in SV content with EN content
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'sv'

# This fills in the gaps in NB content with EN content.
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'nb'

# This fills in the gaps in DA content with EN content.
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'da'

[params]
  mainSections = ['blogg', 'webinar', 'whitepaper', 'solution-brief']

[sitemap]
    changefreq = "daily"
    filename = "sitemap.xml"
    priority = 0.5

[outputs]
    home = ["HTML", "RSS", "SITEMAP"]

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'igor'
    tabWidth = 4
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
  [markup.goldmark.extensions]
    footnote = true

[blackfriday]
fractions = false

[minify]
  minifyOutput = true
