# Swedish - 8081
server {
  listen 8081;
  server_name _;

  root /usr/share/nginx/html/sv;
  index index.html index.htm;

  location ^~ /compliance/downloads/ {
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}

# English - 8082
server {
  listen 8082;
  server_name _;

  root /usr/share/nginx/html/en;
  index index.html index.htm;

  location ^~ /compliance/downloads/ {
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}

# Norwegian Bokmal - 8083
server {
  listen 8083;
  server_name _;

  root /usr/share/nginx/html/nb;
  index index.html index.htm;

  location ^~ /compliance/downloads/ {
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}

# Danish - 8084
server {
  listen 8084;
  server_name _;

  root /usr/share/nginx/html/da;
  index index.html index.htm;

  location ^~ /compliance/downloads/ {
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
